### ISSUE TITLE
Rpi3-alpine-python: udev not found

### ISSUE THREAD

**Issue by VictorGob** [balena-io-library/base-images#520]
I am trying to use a Alpine-python image with pyudev lib. The issue is that pyudev cannot found the udev library:

```
Traceback (most recent call last):
  File "/app/someapp.py", line 647, in <module>
    someapp()
  File "/app/someapp.py", line 89, in someapp
    utm = UTMclient(configuration, log)
  File "/app/someapp.py", line 523, in __init__
    self.connection.port = get_UTM_port(config["UTM"]["ID_VENDOR_ID"])
  File "/app/someapp_pad.py", line 161, in get_UTM_port
    context = pyudev.Context()
  File "/usr/local/lib/python3.6/site-packages/pyudev/core.py", line 64, in __init__
    self._libudev = load_ctypes_library('udev', SIGNATURES, ERROR_CHECKERS)
  File "/usr/local/lib/python3.6/site-packages/pyudev/_ctypeslib/utils.py", line 56, in load_ctypes_library
    raise ImportError('No library named %s' % name)
ImportError: No library named udev
Exception ignored in: <bound method Context.__del__ of <pyudev.core.Context object at 0x75c38db0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pyudev/core.py", line 68, in __del__
    self._libudev.udev_unref(self)
AttributeError: 'Context' object has no attribute '_libudev'
```

Here's part of the Dockerfile:
```
FROM balenalib/raspberrypi3-alpine-python:3.6

ENV UDEV on 

RUN apk update && apk add --upgrade apk-tools && apk upgrade \ 
	&& apk add --no-cache udev tzdata python py3-six py-udev \
	&& pip install --upgrade pip && pip install -r app/requirements.txt


CMD ["python", "/app/someapp.py"]
```
The app works perfect with _"resin/raspberrypi3-python:3"_

Thanks in advance

**Comment by VictorGob** [comment]
It looks like it works with:

```
ENV INITSYSTEM on
ENV UDEV=1
RUN apk update && apk upgrade && apk add --upgrade apk-tools && apk add build-base \ 
	&& apk add --no-cache udev tzdata python3 python3-dev py-udev	
RUN pip3 install --upgrade pip
RUN pip3 install -r app/requirements.txt
```
